### ISSUE TITLE
[Question] Clarification on settings and features

### ISSUE THREAD

**Issue by Freekers** [jr-k/obscreen#24]
I have some questions on several settings and features.

1. On line 12 in the docker-compose.yml file it says:
https://github.com/jr-k/obscreen/blob/6f3546c2bf3e9d0e906f89018b4be77a9eb23674/docker-compose.yml#L12
I.e. this would mean commenting out/removing line 13. But what about the environment variable on line 10; 
https://github.com/jr-k/obscreen/blob/6f3546c2bf3e9d0e906f89018b4be77a9eb23674/docker-compose.yml#L10
Do I still need to keep that one even if I'm not on a Raspberry Pi?

2. What exactly does the AUTOCONFIGURE_REVERSE_PROXY_MODE environmental variable do? 
For example, suppose I use Caddy as reverse proxy, which runs in a separate Docker container; should I enable this variable in this scenario?

3. What is the intended usecase of the Fleetmode?
Suppose I have three screens. This means I run three separate Obscreen instances; one for each screen so three Obscreen containers in total.
I can 'link' these three instances to 1 Obscreen instances sing Fleetmode. This allows me to see the current slide of all three instances in 1 overview in real-time, but I cannot change any of the settings/slides. In order to update the settings/slides, I still need to login manually to each Obscreen instance. Is this expected and the intended usecase of the Fleetmode?

Thank you

**Comment by jr-k** [comment]
1. TLDR: Line 10 is fine for any setup.
Regarding line 13, if you're not on a Raspberry Pi (either for testing purposes or if you're using your own monitor playback logic), you'll need to comment out that line. Otherwise, Docker will attempt to mount a file that doesn't exist, which will disrupt the autoconfiguration process (because the volume will be mounted as a directory). Line 10 doesn't cause any issues, so it's safe to leave it uncommented or not; do as you prefer. Obscreen will populate that file, but nothing will utilize it, which works for me.

2. TLDR: If you're using Caddy, avoid using this setup.
The AUTOCONFIGURE_REVERSE_PROXY_MODE will handle the NGINX server configuration file and the Chromium call in the Raspberry Pi's lx_file automatically (essentially managing the port). I believe a better name for this could be "AUTOCONFIGURE_NGINX." Perhaps I should remove all this setup and let users configure things according to their preferences for better understanding. Another option is to replace this with an environment variable like "PLAYER_URL" and require users to specify the URL explicitly to call from Chromium for lx_file. This would be easier to understand.

3. Question: What is the intended use case for Fleetmode?
Suppose you have three screens, each with its own Raspberry Pi. You need to enable FLEET_MODE for only one "master" server. This will create a new page called "Devices" where you can add your three screens. Now, a "Fleet view" button will take you to a webpage to manage your three screens independently but under one URL. Players are local to each screen and do not share anything. Let me know if you need further instructions; I can create a video to provide a more in-depth look at this feature.

**Comment by Freekers** [comment]
Thank you very much for the clarifications, I appreciate it.

Regarding 2; My recommendation would be indeed to either remove it completely, or change it's name to something like AUTOCONFIGURE_NGINX_RPI, to clarify it's only applicable to Nginx running natively on a RaspberryPi. For example, instead of Caddy, I use Nginx Proxy Manager (https://nginxproxymanager.com/) in case I need to manage more than just a handful of hosts on the same machine. I assume the AUTOCONFIGURE_REVERSE_PROXY_MODE setting would not be applicable in this case either since NPM is also running in a Docker container, which the setting cannot edit.

Isn't PLAYER_URL the same setting as 'External url' on the Settings page in the web interface?

Regarding 3; Ah, I see. In my case, I have three 'Smart TVs' on which I use the internal web browser app to display Obscreen. I don't have any hardware/RPis connected to any of the TVs. I run three (separate) instances of Obscreen on a remote server.

Kind regards

**Comment by jr-k** [comment]
https://github.com/jr-k/obscreen/releases/tag/v1.8
