### ISSUE TITLE
[Feature Request] Synchronize slide transition between Obscreen instances

### ISSUE THREAD

**Issue by Freekers** [jr-k/obscreen#54]
I have three TVs that are connected to three separate Obscreen instances. The goal is to synchronize whenever the slides change on each of the TVs so that they are all in sync. I.e. the transition should happen at the same time for all three TVs.

For this to work, obviously all Obscreen instances need to be able to communicate (securely) with each other. For example, via an API call while making use of the secret key/token.

This feature is only applicable to slides that have the same duration, else it's impossible to sync their transition. Additionally I can imagine that another constraint would be that the affected slides need to be set as 'in the loop', as scheduled or cron slides might disappear from the roster after a while.

I realize that this might be a complex feature request. Nonetheless I think it would be wroth to examine whether or not it's feasible, as this would be an awesome feature to have.

Thank you very much for considering

**Comment by jr-k** [comment]
To understand well, in this setup, what is the slideshow with the feature you described:

Instance 1:
- Youtube URL: for 5s
- URL X: for 60s
- Picture: CRON every monday at 06:00AM

Instance 2:
- Video: for 55s
- URL Y: for 60s
- Picture: CRON every monday at 07:00AM

Instance 3:
- URL Z: for 5s
- Picture: for 60s
- Picture: CRON every monday at 06:00AM

I'm a bit confused

**Comment by Freekers** [comment]
In your example, only the following slides would qualify for the feature described:

- URL X (Instance 1) and URL Y (Instance 2) because both are 60s
- Picture (Instance 1) and Picture (Instance 3) because both have CRON every monday at 06:00AM

For a real world example when this feature would be handy, please take a look at my video: https://imgur.com/a/4cdmLnJ
It would be nice if all screens were in sync. The duration of all slides is set to 10 seconds for slide 1 and 4 seconds for slide 2 on all TVs, but as you can see they are not in sync.

Thank you very much

**Comment by jr-k** [comment]
In my theoretical case:

URL X (Instance 1) and URL Y (Instance 2) because both are 60s
How is this possible? Instance 1 Slide 1 is 5s long before Instance 1 Slide 2 (URL X) and Instance 2 Slide 1 is 55s long. What do you do with the first slide of both instances 1 and 2? Do you skip it? Do you force I1S1 to be 55s long to match I2S1? (or 5s for both)?

To me, the only way this feature can work is in this case (https://github.com/jr-k/obscreen/issues/55):

1 manager where you edit playlists with slides inside
X players subscribe to the playlist
Screens sharing the same playlist are synced to show the same content at the same time
Are you aligned?

**Comment by Freekers** [comment]
> In your case:
> 
> `URL X (Instance 1) and URL Y (Instance 2) because both are 60s` How is this possible? Instance 1 Slide 1 is 5s long before Instance 1 Slide 2 (URL X) and Instance 2 Slide 1 is 55s long. What do you do with the first slide of both instances 1 and 2? Do you skip it? Do you force I1S1 to be 55s long to match I2S1? (or 5s for both)?

Sorry, I misinterpreted your question, my apologies. 

You're right; in order to synchronize slide transitions between obscreen instances, all slides must have the same duration.

For example; instance X has 4 slides and instance Y has 3 slides. It's only possible to sync the transition between both instance X and Y if the slide duration is set to the same interval for each obscreen instance, e.g. 10 seconds.

> To me, the only way this feature can work is in this case (#55):
> 
>     * 1 manager where you edit playlists with slides inside
> 
>     * X players subscribe to one playlist from master
> 
>     * Screens sharing the same playlist id are synced to show the same content at the same time
> 
> 
> Wdyt ?

This approach would work, but is not quite what I had in mind. If I understood correctly, this would mean that the same slides (i.e. content) are displayed on screens for which synchronization has been enabled. However, I prefer to showcase different slides (i.e. content) on each screen yet with while having their transitions synchronized. This should, in theory, be possible if the slide duration is set equal for all slides on all affected screens.

An alternative approach would be that one obscreen instance supports multiple screens, similar to your proposal above. However, each screen would still have it's own playlist, but there's an option to sync slide duration and as such transitions between playlists.

**Comment by jr-k** [comment]
If I try to summarize, I would say that we need to consider two setups and have the right level of abstraction to address these two cases.

## 1. One Raspberry Pi per screen
- There must be a single source of truth for playlists/slides/files => It's a master obscreen instance (aka manager) installed headless on a server.
- There must be a way to display the URL of a playlist automatically on the startup of the Raspberry Pi => It's a slave obscreen instance (aka player).
- It should be possible to link and manage the player instances with their active playlist from the master for efficient fleet management.
- The concept of player instance groups can be added to enable transition synchronization between multiple players with a fixed duration determined in advance.
In both cases, the concept of playlists and the Master/Manager and Slave/Player setup must be added.

## 2. A single Raspberry Pi and simple client browsers displaying the correct URL, which seems to be your case

In fact, this could work exactly like the first case; you would just need to have a single master instance and create three playlists. Each playlist would have its own URL. As you do today, instead of launching three Obscreen instances, you will launch one master and three players. By creating a player group and activating synchronization on this group, you will have the same result in the end.

**Comment by Freekers** [comment]
Yes indeed, I think that would cover this use case 👍 
Thanks for considering this request

**Comment by jr-k** [comment]
It's on track, wip here: https://github.com/jr-k/obscreen/pull/64

**Comment by jr-k** [comment]
New version released: https://github.com/jr-k/obscreen/releases/tag/v1.16

- You can enable time sync in settings
- And you can enable playlists in settings, apply time sync wherever you want. No more Obscreen clone instances. All-in-one.  

Time to feedback :D

Thanks !

**Comment by Freekers** [comment]
Very cool, thank you so much! I will take a look at this tomorrow :)
Thanks!

**Comment by Freekers** [comment]
It works beautifully! Thanks so much for this massive overhaul. It must have been a lot of work but the end result is awesome :)

**Comment by jr-k** [comment]
I'm glad to hear that it works beautifully 😁 It indeed took some effort, but seeing the end result makes it all worthwhile. If you need further assistance, feel free to let me know (here or on obscreen [discord server](https://discord.obscreen.io/))

**Comment by Freekers** [comment]
Unfortunately the Discord invite is invalid :(
