### ISSUE TITLE
static screen whit videos

### ISSUE THREAD

**Issue by valero1120** [jr-k/obscreen#65]
Hello, excellent application, it is very functional, and simple, I only have one problem, the mp4 videos do not play, they remain static, as if they were an image.

**Comment by jr-k** [comment]
I'll deal with it soon, thanks

**Comment by jr-k** [comment]
@valero1120 you can try https://github.com/jr-k/obscreen/issues/59

If you run the browser yourself don't forget to use these flags for chromium browser:
```bash
# chromium or chromium-browser
chromium --disable-features=Translate --ignore-certificate-errors --disable-web-security --disable-restore-session-state --autoplay-policy=no-user-gesture-required --start-maximized --allow-running-insecure-content --remember-cert-error-decisions --noerrdialogs --kiosk --incognito --window-position=0,0 --window-size=1920,1080 --display=:0 https://duckduckgo.com
```

**Comment by valero1120** [comment]
hello friend, look this video, https://app.screencastify.com/v3/watch/zv2S7dRB9CiaxZEo6oMI,

it only happens in the web interface, connecting a display to the RPI 4 does not happen;
I have another question friend, how can I make it so that regardless of the resolution of the image or video, it automatically extends to the dimensions of the monitor, if you can see in the video it shows the images and videos with a black background.

**Comment by jr-k** [comment]
It's normal, they do not play because chrome ask user to interact with the page (a simple click inside the webpage is enough). If you open the console you'll see the error `Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.`. You need to use chrome flag `--autoplay-policy=no-user-gesture-required`. Connecting a raspberry does not happen because I take care of the flag `--autoplay-policy=no-user-gesture-required` for you but in chrome, you need to check yourself. I see you use windows, just type `chrome --autoplay-policy=no-user-gesture-required` in a cmd.exe terminal.

**Comment by jr-k** [comment]
For your 2nd question, I've updated version 1.16 with a fix. Just try with this new revision of 1.16 version. Thanks.

**Comment by valero1120** [comment]
I already have it in a production environment, I have several problems connecting the screen to the raspberry pi 5, with raspian lite os, when the transition makes some screens go black, I think it's something from the refresh rate, and the second thing sometimes The video remains static and looking at the log some connection problems appear, I don't know why.

![image](https://github.com/jr-k/obscreen/assets/40474647/b015aef7-d5e0-462c-8ca4-0ce742a0cf5c)

from crhome
https://1drv.ms/v/s!Avoy5oOmlUTClcI9_hwG4Np32dXnxQ?e=g7vMLK

from screen raspberry
https://1drv.ms/v/s!Avoy5oOmlUTClcI87A76Nd_tKapfWQ?e=bpOcwh
